env:
  CIRRUS_CLONE_DEPTH: 1

macos_catalina_task:
  env:
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
    CC: gcc-10
    CXX: g++-10
    CFLAGS: "-I/usr/local/include -g3 -O0"
  macos_instance:
    image: catalina-base
  install_dependencies_script:
    brew install gmp gettext dejagnu
  create_codesigning_certificate_script:
    - sudo DevToolsSecurity -enable
    - bash -x gdb/contrib/macos-setup-codesign.sh
  build_script:
    - |
      mkdir ../build && cd ../build
      ../cirrus-ci-build/configure          \
        CC=$CC CXX=$CXX                     \
        CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" \
        --enable-codesign=gdb_codesign      \
        --disable-binutils                  \
        --disable-dependency-tracking       \
        --with-gmp=$(brew --prefix gmp)     \
        --with-libgmp-prefix=$(brew --prefix gmp) \
        --prefix=$HOME/GDB/
      make -j 12
      make install-gdb
      tar -cf $HOME/gdb.tar $HOME/GDB
  test_script:
    - |
      echo 'set startup-with-shell off' > $HOME/.gdbinit
      echo 'set debug darwin 12' >> $HOME/.gdbinit
      cd ../build
      make check-gdb RUNTESTFLAGS="CC_FOR_TARGET=$CC CXX_FOR_TARGET=$CXX" TESTS=gdb.base/return.exp GDB_DEBUG=infrun
      # make check RUNTESTFLAGS="CC_FOR_TARGET=$CC CXX_FOR_TARGET=$CXX" TESTS=gdb.base/return.exp GDB_DEBUG=infrun
      # bash <(head outputs/gdb.base/return/gdb.cmd.1 | tr -d \\n && echo -x outputs/gdb.base/return/gdb.in.1)
      # bash <(ghead -c -1 outputs/gdb.base/return/gdb.cmd.1 && echo -x outputs/gdb.base/return/gdb.in.1)
