env:
  CIRRUS_CLONE_DEPTH: 1

macos_catalina_task:
  env:
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
    CC: gcc-11
    CXX: g++-11
    CFLAGS: "-I/usr/local/include -g3 -O0"
  macos_instance:
    image: catalina-base
  install_dependencies_script:
    brew install gmp gettext dejagnu
  create_codesigning_certificate_script:
    - sudo DevToolsSecurity -enable
    - bash -x gdb/contrib/macos-setup-codesign.sh
  build_script:
    - |
      mkdir ../build && cd ../build
      ../binutils-gdb/configure             \
        CC=$CC CXX=$CXX                     \
        CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" \
        --enable-codesign=gdb_codesign      \
        --disable-binutils                  \
        --disable-dependency-tracking       \
        --with-gmp=$(brew --prefix gmp)     \
        --with-libgmp-prefix=$(brew --prefix gmp) \
        --prefix=$HOME/GDB/
      make -j 3
      make install-gdb
      tar -cf $HOME/gdb.tar $HOME/GDB
  test_script:
    - |
      echo 'set startup-with-shell off' > $HOME/.gdbinit
      cd ../build
      make check-gdb RUNTESTFLAGS="CC_FOR_TARGET=$CC CXX_FOR_TARGET=$CXX"
