name: CI

on: [push, pull_request]

jobs:
  macos:
    name: ${{matrix.vector.jobname}} (${{matrix.vector.pool}})
    strategy:
      fail-fast: false
      matrix:
        vector:
          - jobname: osx-gcc
            cc: gcc-11
            cxx: g++-11
            pool: macos-10.15
          - jobname: osx-clang
            cc: clang
            cxx: clang++
            pool: macos-10.15
    env:
      CC: ${{matrix.vector.cc}}
      CXX: ${{matrix.vector.cc}}
      jobname: ${{matrix.vector.jobname}}
      runs_on_pool: ${{matrix.vector.pool}}
      CFLAGS: -I/usr/local/include
    runs-on: ${{matrix.vector.pool}}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run:  brew install gmp gettext dejagnu
    - name: Setup codesigning certificate
      run:  |
          sudo DevToolsSecurity -enable
          bash -x gdb/contrib/macos-setup-codesign.sh
    - name: Build
      run: |
          mkdir ../build && cd ../build
          ../binutils-gdb/configure CC=$CC CXX=$CXX \
            CFLAGS=$CFLAGS CXXFLAGS=$CFLAGS \
            --enable-codesign=gdb_codesign \
            --disable-binutils
          make -j 3
    - name: Test
      run: |
          cd ../build
          make check-gdb -j 3
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
  
